### ISSUE TITLE
Provided install instruction doesn't works

### ISSUE THREAD

**Issue by nosuchip** [cgewecke/eth-gas-reporter#104] opened 2018-09-23 14:19 UTC
- Installing: ` npm install --save-dev eth-gas-reporter`
- Updating `truffle.js`:
   ```
  mocha: {
    reporter: 'eth-gas-reporter',
    reporterOptions: {
      currency: 'USD',
      gasPrice: 10
    }
  }
   ```
- Starting test that call single contract method (contract is not abstract or empty): `npm test`

Results:
```
TypeError: Cannot read property 'gasUsed' of undefined
    at names.forEach.name (/home/alp/proj/coinbet/smartcontracts/node_modules/eth-gas-reporter/gasStats.js:396:52)
    at Array.forEach (<anonymous>)
    at files.forEach.file (/home/alp/proj/coinbet/smartcontracts/node_modules/eth-gas-reporter/gasStats.js:371:11)
    at Array.forEach (<anonymous>)
    at Object.mapMethodsToContracts (/home/alp/proj/coinbet/smartcontracts/node_modules/eth-gas-reporter/gasStats.js:367:9)
    at Runner.Gas.runner.on (/home/alp/proj/coinbet/smartcontracts/node_modules/eth-gas-reporter/index.js:119:65)
    at emitNone (events.js:111:20)
    at Runner.emit (events.js:208:7)
    at start (/home/alp/proj/coinbet/smartcontracts/node_modules/mocha/lib/runner.js:826:10)
    at Runner.run (/home/alp/proj/coinbet/smartcontracts/node_modules/mocha/lib/runner.js:854:5)
    at Mocha.run (/home/alp/proj/coinbet/smartcontracts/node_modules/mocha/lib/mocha.js:572:17)
    at /home/alp/proj/coinbet/smartcontracts/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:125:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! Test failed.  See above for more details.
```

Some internals of call:
```
name=Bookmaker,
receipt=undefined,
networkDeployment={"events":{"0x935856f3097b8ffdc9b085ee61554545ca742030543944cd41d542d796b51af5":{"anonymous":false,"inputs":[{"indexed":false,"name":"packed","type":"bytes32"},{"indexed":false,"name":"sender","type":"address"},{"indexed":false,"name":"amount","type":"uint256"},{"indexed":false,"name":"isPartial","type":"bool"},{"indexed":false,"name":"partialAmount","type":"uint256"},{"indexed":false,"name":"partialRefund","type":"uint256"}],"name":"BetMatched","type":"event"},"0x68a467eb69c9153bb488325db1dec0f7ffc2197d32b3532509c15e9b72da40bf":{"anonymous":false,"inputs":[{"indexed":false,"name":"packed","type":"bytes32"},{"indexed":false,"name":"sender","type":"address"},{"indexed":false,"name":"amount","type":"uint256"},{"indexed":false,"name":"isPartial","type":"bool"}],"name":"BetReturned","type":"event"},"0x686d72213469ef6c12d025ee2ba86e632776edb3735da5a259b88ede34865e5c":{"anonymous":false,"inputs":[{"indexed":false,"name":"packed","type":"bytes32"},{"indexed":false,"name":"homeOrAway","type":"uint256"},{"indexed":false,"name":"addr","type":"address"},{"indexed":false,"name":"amount","type":"uint256"},{"indexed":false,"name":"isPartial","type":"bool"}],"name":"BetPaid","type":"event"}},"links":{"MyLib":"0xf5ca4f56211c3b879902bd43b290d2160ae0dbaa"}},
networkId=1537711868842,
networkDeployment.transactionHash=undefined

contract.networks={"1537711868842":{"events":{"0x935856f3097b8ffdc9b085ee61554545ca742030543944cd41d542d796b51af5":{"anonymous":false,"inputs":[{"indexed":false,"name":"packed","type":"bytes32"},{"indexed":false,"name":"sender","type":"address"},{"indexed":false,"name":"amount","type":"uint256"},{"indexed":false,"name":"isPartial","type":"bool"},{"indexed":false,"name":"partialAmount","type":"uint256"},{"indexed":false,"name":"partialRefund","type":"uint256"}],"name":"BetMatched","type":"event"},"0x68a467eb69c9153bb488325db1dec0f7ffc2197d32b3532509c15e9b72da40bf":{"anonymous":false,"inputs":[{"indexed":false,"name":"packed","type":"bytes32"},{"indexed":false,"name":"sender","type":"address"},{"indexed":false,"name":"amount","type":"uint256"},{"indexed":false,"name":"isPartial","type":"bool"}],"name":"BetReturned","type":"event"},"0x686d72213469ef6c12d025ee2ba86e632776edb3735da5a259b88ede34865e5c":{"anonymous":false,"inputs":[{"indexed":false,"name":"packed","type":"bytes32"},{"indexed":false,"name":"homeOrAway","type":"uint256"},{"indexed":false,"name":"addr","type":"address"},{"indexed":false,"name":"amount","type":"uint256"},{"indexed":false,"name":"isPartial","type":"bool"}],"name":"BetPaid","type":"event"}},"links":{"MyLib":"0xf5ca4f56211c3b879902bd43b290d2160ae0dbaa"}}}
```

OS: Linux Mint 18
Node: 8.11.3
Truffle: 4.1.14
Ganache-cli: 6.1.8

**Comment by cgewecke** [comment] 2018-09-23 16:56
@nosuchip Hi, some questions...

+ Do your tests run without problems *without* the gas reporter?
+ Could you upgrade to the latest eth-gas-reporter version? (it looks like you might be behind a little based on the stack trace)
+ Do you have a link to your project or a way of reproducing this?

**Comment by nosuchip** [comment] 2018-09-25 06:06
@cgewecke thanks for response.
- Yes, tests are passed without gas reporter.
- I just installed it from npm, so, suppose I am working with the latest version.
- I prepared minimalistic repo for you: https://github.com/nosuchip/eth-gas-reporter-bug

Mopst interesting thing that result depends on contract that even not mentioned in test, see README.me in repo.

**Comment by elenadimitrova** [comment] 2018-11-14 15:07
We have the same issue after upgrading to `0.1.12` however worth noting that [we upgraded a number of packages](https://github.com/JoinColony/colonyNetwork/pull/435/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R68) at the same time and atm I am not convinced it's ` eth-gas-reporter` that's causing it.

**Comment by elenadimitrova** [comment] 2018-11-14 15:54
After some more investigation the error is thrown because a transaction receipt [here](https://github.com/cgewecke/eth-gas-reporter/blob/master/gasStats.js#L392) is `undefined`. This appears to be due to the fact the `networkDeployment.transactionHash` of this particular contract is `undefined` as well, leading to the receipt not being found too. In our case we have a number of previously successful `networkDeployment` objects being populated with the correct `transactionHash`. The only thing different I see on this instance is that the contract contains linked libraries, here it is `SafeMath`.

```
networkDeployment { events:
   { '0x2f304925f4f66741b976d6f4f9a127315b8ef823c6e2a3b08895e5b11579bc78':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskAdded',
        type: 'event',
        signature: '0x2f304925f4f66741b976d6f4f9a127315b8ef823c6e2a3b08895e5b11579bc78' },
     '0xc6075fecdfad034c5ddbf812f6b39bce70b4724543f1d15bf932e65ee7be1dd2':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskBriefChanged',
        type: 'event',
        signature: '0xc6075fecdfad034c5ddbf812f6b39bce70b4724543f1d15bf932e65ee7be1dd2' },
     '0x51d2f483287200aa828e3d30928144e3646415cc15504d037be726df65b11e99':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskDueDateChanged',
        type: 'event',
        signature: '0x51d2f483287200aa828e3d30928144e3646415cc15504d037be726df65b11e99' },
     '0x0b32a019cd79ae388c40a65e0283ae1295020ae74051045df627be08236e5a46':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskDomainChanged',
        type: 'event',
        signature: '0x0b32a019cd79ae388c40a65e0283ae1295020ae74051045df627be08236e5a46' },
     '0x02ee180b02aaa1a91109804531fb919a455619ecf31f73781bbfeffffb633adc':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskSkillChanged',
        type: 'event',
        signature: '0x02ee180b02aaa1a91109804531fb919a455619ecf31f73781bbfeffffb633adc' },
     '0x05efeda248bd9dbfabd135b277d71586c21c155d74dbaa18f71c4f38eeecb72c':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskRoleUserChanged',
        type: 'event',
        signature: '0x05efeda248bd9dbfabd135b277d71586c21c155d74dbaa18f71c4f38eeecb72c' },
     '0x7f29b779aec5ba01774aa02611705a4a7a13c4732e015e28d53661b581e16527':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskDeliverableSubmitted',
        type: 'event',
        signature: '0x7f29b779aec5ba01774aa02611705a4a7a13c4732e015e28d53661b581e16527' },
     '0x1d948e48ee7eb574df4bb4f648f54a9f183845cfa733d1b3849e424052b1a60e':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskWorkRatingRevealed',
        type: 'event',
        signature: '0x1d948e48ee7eb574df4bb4f648f54a9f183845cfa733d1b3849e424052b1a60e' },
     '0xc40773f63181c220f9ade90c8ecc57330e44f2ba91501608ac4c37cac84f96bd':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskFinalized',
        type: 'event',
        signature: '0xc40773f63181c220f9ade90c8ecc57330e44f2ba91501608ac4c37cac84f96bd' },
     '0x1aa8a90c7d7a86bac690072d3f3d726bb8ebbe1989e158530440963f04c11eb2':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskCanceled',
        type: 'event',
        signature: '0x1aa8a90c7d7a86bac690072d3f3d726bb8ebbe1989e158530440963f04c11eb2' },
     '0xc1fa7142cfb933d0855114a3bffde296944c30b727f297c14d0db4d553d3a5c7':
      { anonymous: false,
        inputs: [Array],
        name: 'TaskCompleted',
        type: 'event',
        signature: '0xc1fa7142cfb933d0855114a3bffde296944c30b727f297c14d0db4d553d3a5c7' },
     '0xdc725e59177226413e53f3af2d4ce462afe057a50f64a5cc1f4ba68995ee6e85':
      { anonymous: false,
        inputs: [Array],
        name: 'DomainAdded',
        type: 'event',
        signature: '0xdc725e59177226413e53f3af2d4ce462afe057a50f64a5cc1f4ba68995ee6e85' },
     '0xd6997e5e17ae120ac7d1044a686557c5090d47dc7183284ac240069c3b69a5cc':
      { anonymous: false,
        inputs: [Array],
        name: 'PotAdded',
        type: 'event',
        signature: '0xd6997e5e17ae120ac7d1044a686557c5090d47dc7183284ac240069c3b69a5cc' },
     '0x1abebea81bfa2637f28358c371278fb15ede7ea8dd28d2e03b112ff6d936ada4':
      { anonymous: false,
        inputs: [Array],
        name: 'LogSetAuthority',
        type: 'event',
        signature: '0x1abebea81bfa2637f28358c371278fb15ede7ea8dd28d2e03b112ff6d936ada4' },
     '0xce241d7ca1f669fee44b6fc00b8eba2df3bb514eed0f6f668f8f89096e81ed94':
      { anonymous: false,
        inputs: [Array],
        name: 'LogSetOwner',
        type: 'event',
        signature: '0xce241d7ca1f669fee44b6fc00b8eba2df3bb514eed0f6f668f8f89096e81ed94' } },
  links: { SafeMath: '0x70aFe216F90B156370E525F52623Cb5Fd018D2e0' } }
```

**Comment by elenadimitrova** [comment] 2018-11-14 16:04
ok I found the cause and a workaround. If you have a contract that links to a library but it is not deployed, this happens, e.g. in our case this was
```
module.exports = (deployer) => {
  deployer.deploy(SafeMath);
  deployer.link(SafeMath, ColonyTask);
}
```
If you explicitly deploy the missing contract then the contract definition then `networkDeployment.transactionHash` is populated and `receipt` is also gotten correctly.
```
module.exports = (deployer) => {
  deployer.deploy(SafeMath);
  deployer.link(SafeMath, ColonyTask);
  deployer.deploy(ColonyTask);
}
```

**Comment by nosuchip** [comment] 2018-11-14 16:06
@elenadimitrova probably it is different issue. I have all contracts deployed explicitly and still have issue described initially.

**Comment by elenadimitrova** [comment] 2018-11-14 16:12
It seems like very much the same issue as the error you are getting is also caused by a missing `transactionHash` for a contract which contains linked Libraries.

**Comment by nosuchip** [comment] 2018-11-14 16:14
Could you provide minimal repo example where it can be reproduced? In one above all contracts deployed but issue still exists with latest packages version.

**Comment by amhed** [comment] 2018-12-16 06:57
I have this same problem. 

```
> $ truffle version                                                                                                                                          
⬡ Node 8.11.4
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
```

I silenced this by modyfying the report source code on `node_modules` and checking for `receipt != null`

```js
      if (networkDeployment) {
        const code = sync.getCode(networkDeployment.address);
        const hash = sha1(code);
        contractNameFromCodeHash[hash] = name;
        const receipt = sync.getTransactionReceipt(networkDeployment.transactionHash.toString());
        if (!!receipt) {
          contractInfo.gasData.push(parseInt(receipt.gasUsed, 16));
        }
      }
```

But this is not a long term solution / I need to depend on the package instead of doing it manually.

**Comment by jamesmorgan** [comment] 2019-05-02 14:33
I also get this issue, fine without gas reporter. Using latest truffle and solidity 5.0.0 - any ideas?

**Comment by cgewecke** [comment] 2019-05-02 16:49
@jamesmorgan Could you see if downgrading to 0.1.10 works? There may still be problems because the parser needs to be updated here to handle latest solidity. 

Am doing some maintenance on this shortly and will ping this issue when a new version is published.

**Comment by jamesmorgan** [comment] 2019-05-03 13:13
Ah great, ye downgrading works 👍  thanks

**Comment by cgewecke** [comment] 2019-05-07 20:04
This should be fixed in `0.2.0`. Have added a test similar to @nosuchip's reproduction case - thanks to everyone for such great debugging.

**Closed by cgewecke** 2019-05-07 20:04 UTC

**Comment by fodisi** [comment] 2020-02-27 05:47
I just ran into this issue. My local environment is:
OS: Ubuntu 18.04.4 LTS 64-bit
Truffle v5.1.14 (core: 5.1.14)
Solidity - 0.5.16 (solc-js)
Node v10.19.0
Web3.js v1.2.1
eth-gas-reporter 0.2.15

The issue happened after I deleted a couple of contracts and removed them from my migration script file.

After some investigation, I noticed in file `gasData.js` the call to the method `.getContractNames(file)` (line 43) was still returning the name of one of the deleted files, and when trying to process it, it would throw this error (it couldn't get a valid receipt for the invalid transactionHash, which was not null - but probably some stale value).

I identified that my folder `build/contracts` still contained the ABI .json files for the deleted contracts.
So as a workaround, I delete the entire `build/contracts/` folder and run `truffle compile --all` to recompile the contracts.

It fixed the issue for me. Not sure why this was important, but maybe something related to inheritance between existing and deleted contracts ( :thinking:  :question: ).


PS: After I fixed it, I tried to reproduce the issue again but couldn't. I'll try again when I have some spare time and if I'm able to reproduce it, I'll try to submit a PR with a fix or at least, open another issue with more specific details on how to reproduce it.

**Comment by cgewecke** [comment] 2020-02-27 18:32
@fodisi Thanks for analyzing this! 

> it couldn't get a valid receipt for the invalid transactionHash, which was not null - but probably some stale value

Yes, I wonder if a simple remedy might be to wrap some of this logic in a try/catch and ignore stale deployments...

https://github.com/cgewecke/eth-gas-reporter/blob/e48894857888f7cfe1c1886bdef0f6a7916be491/lib/gasData.js#L62-L68

I'm going to open this as a separate issue so it doesn't get lost...
